# Generated by Django 2.2 on 2019-04-23 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0001_initial'),
        ('student', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.SlugField(unique=True)),
                ('amount', models.FloatField()),
                ('remark', models.CharField(default='-', max_length=55)),
                ('registration_id', models.CharField(max_length=55)),
                ('update', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_id', models.SlugField(unique=True)),
                ('amount', models.FloatField(default=0)),
                ('balance', models.FloatField(default=0)),
                ('type', models.CharField(max_length=50)),
                ('c_o_e', models.CharField(max_length=75)),
                ('status', models.BooleanField(default=True)),
                ('cancel', models.BooleanField(default=False)),
                ('update', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='event.EventRecord')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='student.StudentRecord')),
                ('transaction_id', models.ManyToManyField(to='registration.TransactionRecord')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
