# Generated by Django 2.1.4 on 2018-12-26 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationrecord',
            name='balance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='registrationrecord',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registrationrecord',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
