# Generated by Django 2.1.1 on 2018-12-06 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationrecord',
            name='user',
        ),
        migrations.AddField(
            model_name='registrationrecord',
            name='student',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='student.StudentRecord'),
        ),
        migrations.AlterField(
            model_name='registrationrecord',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.EventRecord'),
        ),
    ]
