# Generated by Django 2.1.1 on 2018-12-06 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionrecord',
            name='remark',
            field=models.CharField(default='-', max_length=55),
        ),
    ]
