# Generated by Django 2.1.1 on 2018-12-06 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20181206_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationrecord',
            name='student',
            field=models.ForeignKey(default='student', on_delete=django.db.models.deletion.CASCADE, to='student.StudentRecord'),
        ),
    ]
