# Generated by Django 2.1 on 2018-10-11 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150)),
                ('roll_no', models.CharField(max_length=30)),
                ('college_name', models.CharField(max_length=200)),
                ('branch', models.CharField(max_length=10)),
                ('year', models.CharField(max_length=50)),
                ('sem', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('registered_event_code', models.CharField(max_length=55)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GuestlectureStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150)),
                ('roll_no', models.CharField(max_length=30)),
                ('college_name', models.CharField(max_length=200)),
                ('branch', models.CharField(max_length=10)),
                ('year', models.CharField(max_length=50)),
                ('sem', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('registered_event_code', models.CharField(max_length=55)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SeminarStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150)),
                ('roll_no', models.CharField(max_length=30)),
                ('college_name', models.CharField(max_length=200)),
                ('branch', models.CharField(max_length=10)),
                ('year', models.CharField(max_length=50)),
                ('sem', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('registered_event_code', models.CharField(max_length=55)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StudentRecordCompetition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('registered_event_code', models.CharField(max_length=55)),
                ('payment_id', models.SlugField(unique=True)),
                ('c_o_e', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='StudentRecordGuestlecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('registered_event_code', models.CharField(max_length=55)),
                ('payment_id', models.SlugField(unique=True)),
                ('c_o_e', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='StudentRecordSeminar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('registered_event_code', models.CharField(max_length=55)),
                ('payment_id', models.SlugField(unique=True)),
                ('c_o_e', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='StudentRecordTraining',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('registered_event_code', models.CharField(max_length=55)),
                ('payment_id', models.SlugField(unique=True)),
                ('c_o_e', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='StudentRecordWorkshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('registered_event_code', models.CharField(max_length=55)),
                ('payment_id', models.SlugField(unique=True)),
                ('c_o_e', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150)),
                ('roll_no', models.CharField(max_length=30)),
                ('college_name', models.CharField(max_length=200)),
                ('branch', models.CharField(max_length=10)),
                ('year', models.CharField(max_length=50)),
                ('sem', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('registered_event_code', models.CharField(max_length=55)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WorkshopStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150)),
                ('roll_no', models.CharField(max_length=30)),
                ('college_name', models.CharField(max_length=200)),
                ('branch', models.CharField(max_length=10)),
                ('year', models.CharField(max_length=50)),
                ('sem', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('registered_event_code', models.CharField(max_length=55)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='StudentRecord',
        ),
        migrations.AddField(
            model_name='competitionrecord',
            name='c_o_e',
            field=models.CharField(default=0, max_length=75),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guestlecturerecord',
            name='c_o_e',
            field=models.CharField(default=0, max_length=75),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seminarrecord',
            name='c_o_e',
            field=models.CharField(default=0, max_length=75),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainingrecord',
            name='c_o_e',
            field=models.CharField(default=0, max_length=75),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workshoprecord',
            name='c_o_e',
            field=models.CharField(default=0, max_length=75),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='competitionrecord',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='guestlecturerecord',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='seminarrecord',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='trainingrecord',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='workshoprecord',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
