# Generated by Django 2.1 on 2018-09-09 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrecord',
            name='registered_event_code',
            field=models.CharField(default=0, max_length=55, unique=True),
            preserve_default=False,
        ),
    ]
