# Generated by Django 2.1 on 2018-10-12 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrecordcompetition',
            name='paid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentrecordguestlecture',
            name='paid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentrecordseminar',
            name='paid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentrecordtraining',
            name='paid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentrecordworkshop',
            name='paid',
            field=models.IntegerField(default=0),
        ),
    ]
