# Generated by Django 2.1 on 2018-10-11 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20181011_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrecordcompetition',
            name='paid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentrecordguestlecture',
            name='paid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentrecordseminar',
            name='paid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentrecordtraining',
            name='paid',
            field=models.IntegerField(default=0),
        ),
    ]
