# Generated by Django 2.1.1 on 2018-10-25 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20181025_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentrecordcompetition',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_student', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentrecordcompetition',
            name='registered_event_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition', to='events.CompetitionRecord'),
        ),
        migrations.AlterField(
            model_name='studentrecordguestlecture',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_student', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentrecordguestlecture',
            name='registered_event_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_event', to='events.GuestLectureRecord'),
        ),
        migrations.AlterField(
            model_name='studentrecordseminar',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seminar_student', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentrecordseminar',
            name='registered_event_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seminar_event', to='events.SeminarRecord'),
        ),
        migrations.AlterField(
            model_name='studentrecordtraining',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_student', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentrecordtraining',
            name='registered_event_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_event', to='events.TrainingRecord'),
        ),
        migrations.AlterField(
            model_name='studentrecordworkshop',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshop_student', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentrecordworkshop',
            name='registered_event_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshop_event', to='events.WorkshopRecord'),
        ),
    ]
