# Generated by Django 2.1 on 2018-09-10 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20180910_0145'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthRecordguest_lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='MonthRecordseminar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='MonthRecordtraining',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='MonthRecordworkshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.RenameModel(
            old_name='MonthRecord',
            new_name='MonthRecordcompetition',
        ),
    ]
