# Generated by Django 2.1 on 2018-09-10 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20180910_0539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitionrecord',
            name='eligible_sections',
        ),
        migrations.RemoveField(
            model_name='guestlecturerecord',
            name='eligible_sections',
        ),
        migrations.RemoveField(
            model_name='seminarrecord',
            name='eligible_sections',
        ),
        migrations.RemoveField(
            model_name='trainingrecord',
            name='eligible_sections',
        ),
        migrations.RemoveField(
            model_name='workshoprecord',
            name='eligible_sections',
        ),
    ]
