# Generated by Django 2.1 on 2018-09-30 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20180910_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshoprecord',
            name='registered',
            field=models.CharField(default='0000000', editable=False, max_length=7),
        ),
    ]
