# Generated by Django 2.1.1 on 2018-12-04 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventrecord',
            name='outside_student',
            field=models.IntegerField(default=0),
        ),
    ]
