# Generated by Django 2.1.1 on 2018-12-04 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20181205_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventrecord',
            name='event_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='eventrecord',
            name='registration_end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='eventrecord',
            name='registration_start',
            field=models.DateTimeField(),
        ),
    ]
