# Generated by Django 2.2 on 2019-04-22 19:09

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_eventrecord_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventrecord',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='eventrecord',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
