# Generated by Django 2.2 on 2019-04-22 19:41

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20190423_0039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventrecord',
            name='content',
        ),
        migrations.AddField(
            model_name='eventrecord',
            name='learning_outcome_1',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='eventrecord',
            name='learning_outcome_2',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='eventrecord',
            name='learning_outcome_3',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='eventrecord',
            name='learning_outcome_4',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='eventrecord',
            name='learning_outcome_5',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='eventrecord',
            name='learning_outcome_6',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='eventrecord',
            name='pre_requisites_1',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='eventrecord',
            name='pre_requisites_2',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='eventrecord',
            name='pre_requisites_3',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='eventrecord',
            name='resource_person_data',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='eventrecord',
            name='venue',
            field=models.CharField(max_length=50),
        ),
    ]
