# Generated by Django 2.2 on 2019-04-22 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_auto_20190423_0111'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventrecord',
            name='event_pic',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventrecord',
            name='resource_person_pic',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
