# Generated by Django 2.2 on 2019-04-23 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_auto_20190423_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventrecord',
            name='event_pic',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='eventrecord',
            name='learning_outcome_1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='eventrecord',
            name='learning_outcome_2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='eventrecord',
            name='learning_outcome_3',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='eventrecord',
            name='learning_outcome_4',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='eventrecord',
            name='learning_outcome_5',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='eventrecord',
            name='learning_outcome_6',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='eventrecord',
            name='resource_person_pic',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
